config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :lists do
    resources :products
  end
  root "lists#index"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
    validates_presence_of :name
    validates_uniqueness_of :name
    has_many :products, dependent: :destroy
    
    def update_status_if_all_products_purchased
        if products.all? { |product| product.purchased? }
          update(status: 'all_purchased')
        else
          update(status: 'partial_purchased')
        end
    end
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :list

    after_save :update_list_status

    def update_list_status
        list.update_status_if_all_products_purchased if list.update_status_if_all_products_purchased
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to list_url(@list), notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        update_products_purchased_status if list_params[:product_ids].present?
        format.html { redirect_to list_url(@list), notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

 # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  
    def update_products_purchased_status
      @list.products.where(id: list_params[:product_ids]).update_all(purchased: true)
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name, product_ids: [])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_list
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = @list.products.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = @list.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to list_products_path(@list, @product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update(product_params)
        @product.mark_purchased! if @product.purchased? 
        format.html { redirect_to list_product_url(@product.list, @product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to list_products_path(@list), notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:list_id])
    end

    def set_product
      @product = @list.products.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :purchased)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Inicial page", root_path, class: 'navbar-brand' %>
  <div class="collapse navbar-collapse">
    <div class="navbar-nav">
      <%= link_to 'Any link', '#', class: 'nav-item nav-link' %>
    </div>
  </div>
</nav>

<main class="container" role="main">
  <%= yield %>
</main>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: [list]) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %> <br>
    
        
    <%= form.submit "Salvar"%>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>">
</div>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Show this list", [@list] %> |
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>All Lists</h1>

<div id="lists">
  <table class="box">
    <thead>
        <tr>
          <th scope="col"> Name List </th>
          <th> -- </th>
          <th scope="col"> Status </th>
        </tr>
    </thead>
  </table> 
  <% @lists.each do |list| %>
    <%= render list %>
    <p class=list_status>
      <%= link_to list.name, [list] %>
      
      <%= list.status %> 
    </p>
  <% end %>

</div>


<%= link_to "New list", new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="lists-all">
  <table class="box">
    <thead>
      <tr>
        <th scope="col">List</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @list.name %></td>
      </tr>
    </tbody>
  </table>
   
  <div class="button-options">
    <%= link_to "Edit list", edit_list_path(@list) %> |
    <%= link_to "Access to products", list_products_path(@list) %> |
    <%= link_to "Back to lists", lists_path(@list) %>
    <%= button_to "Destroy this list", [@list], method: :delete %>
  </div>
</div>

app/views/products/_form.html.erb
<%= form_with(model: [@list, product]) do |form| %>
  
    <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.submit %>
    
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
    <h1>Show Product</h1>
    <p><%= product.name %></p>
    
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", list_products_path(@list) %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Produtos</h1>

<%= form_for @list do |f| %>
  <%= hidden_field_tag 'list_id', @list.id %>
  <% @list.products.each do |product| %>
    <%= check_box_tag "list[product_ids][]", product.id, product.purchased %>
    <%= product.name %> 
    
    <%= link_to "Show",[@list, product] %>
    <br>
  <% end %>
  <%= f.submit "Salvar" %>
<% end %>

  <br>
<%= link_to "Novo Produto", new_list_product_path(@list) %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", list_products_path(@list) %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>
<div>
  <%= link_to "Edit this product", edit_list_product_path(@list, @product), method: :get %> |
  <%= link_to "Back to products", list_products_path(@list) %>
  <%= button_to "Destroy this product", [@list, @product], method: :delete %>
</div>